# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exPose' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for exPose

  pod 'SQLite.swift', '~> 0.11.6'

  target 'exPoseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'exPoseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
