# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exPose' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for exPose

  platform :ios, '9.0'
  use_frameworks!

  pod 'Clarifai-Apple-SDK', '~> 3.0.0'

  target 'exPoseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'exPoseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
